### ISSUE TITLE
Bullet physics engine integration?

### ISSUE THREAD

**Issue by kkimdev** [abma/streflop#2]
Deterministic physics simulation is also a big topic.  But to my knowledge, there is no well maintained physics engine that supports it.

Bullet is often considered the best quality open source physics engine available now, and their underlying floating point spec is well encapsulated in one file, https://github.com/bulletphysics/bullet3/blob/master/src/Bullet3Common/b3Scalar.h  so it will be easy to integrate and can be a good demonstration I think.

**Comment by abma** [comment]
five years later:

sorry i've missed this issue. Thats a feature request for the bulletphysics engine.

that was the wrong issue tracker, sorry!
